blank_issues_enabled: true
contact_links:
  - name: Notesfriend Discord Community
    url: https://go.notesfriend.com/discord
    about: Reach out to us directly & discuss your issues, suggestions & other feedback!
